services:
  twingate:
    image: twingate/connector:latest
    container_name: twingate
    restart: unless-stopped
    pull_policy: always
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    environment:
      TWINGATE_NETWORK: ""
      TWINGATE_ACCESS_TOKEN: ""
      TWINGATE_REFRESH_TOKEN: ""
      TWINGATE_LABEL_HOSTNAME: "${HOSTNAME}"
      TWINGATE_LABEL_DEPLOYED_BY: "docker"