apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  storage:
    size: 1Gi
  superuserSecret:
    name: immich-db-secrets
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secrets