---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-media
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-media
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: immich-media
    volumeAttributes:
      source: "//192.168.178.3/immich"
    nodeStageSecretRef:
      name: immich-smb-secrets
      namespace: immich
  mountOptions:
    - vers=3.0
    - ro
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: immich-media
  volumeName: immich-media
  resources:
    requests:
      storage: 1Ti