apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-storage
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mailu-storage"
  hostPath:
    path: /var/mnt/zfs/mailu/mailu-storage
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist