apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "redis-data"
  hostPath:
    path: /var/mnt/zfs/mailu/redis-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist