apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-secrets
  data:
  - secretKey: cloudflare_api_token_secret
    remoteRef:
      key: kv/Kubernetes
      property: cloudflare_api_token_secret