--- 
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-smtp-secrets
  namespace: mealie
  argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: mealie-smtp-secrets
  data:
    - secretKey: smtpPassword
      remoteRef:
        key: kv/kubernetes/mealie
        property: smtpPassword