---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-db-secrets
  namespace: mealie
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: mealie-db-secrets
  data:
    - secretKey: username
      remoteRef:
        key: kv/kubernetes/mealie
        property: dbUser
    - secretKey: password
      remoteRef:
        key: kv/kubernetes/mealie
        property: dbPassword