[global]
keyboard = "de"
country = "de"
fqdn = "heimdall.local"
mailto = "root@test.com"
timezone = "Europe/Berlin"
root-password = "12345678"

[network]
source = "from-answer"
cidr = "192.168.178.3"
dns = "192.168.178.131"
gateway = "192.168.178.1"

[disk-setup]
filesystem = "ext4"
disk-list = ["sda"]