[global]
keyboard = "de"
country = "de"
fqdn = "heimdall.local"
mailto = "root@test.com"
timezone = "Europe/Berlin"
root-password = "12345678"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"
disk-list = ["sda"]