apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs
  annotations:
    argocd.argoproj.io/hook: PostSync
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/mnt/zfs
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
