apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "jellyfin-media"
  hostPath:
    path: /var/mnt/zfs/media
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
