---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.178.3
    path: /mnt/hdd/media
  mountOptions:
    - nfsvers=4.1
    - ro
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: jellyfin-media
  resources:
    requests:
      storage: 1Ti