apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    solvers:
    - dns01:
      cloudflare:
        apiTokenSecretRef:
        name: cloudflare_secrets
        key: cloudflare_api_token_secret