apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: "dawid.imb@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
          name: cloudflare-secrets
          key: cloudflare_api_token_secret