apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-secrets
  namespace: newt
  argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: newt-secrets
  data:
    - secretKey: PANGOLIN_ENDPOINT
      remoteRef:
        key: kv/kubernetes/newt
        property: endpointKey
    - secretKey: NEWT_ID
      remoteRef:
        key: kv/kubernetes/newt
        property: idKey
    - secretKey: NEWT_SECRET
      remoteRef:
        key: kv/kubernetes/newt
        property: secretKey