---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts'
    chart: csi-driver-smb
    targetRevision: 1.20.1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true