---
services:
  omni:
    image: ghcr.io/siderolabs/omni:latest
    container_name: omni
    read_only: true
    # user
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./omni.asc:/omni.asc:ro
      - /opt/omni/sqlite:/_out/sqlite:rw
      - /opt/omni/etcd:/_out/etcd:rw
    command:
      - --private-key-source=file:///omni.asc
      - --sqlite-storage-path=/_out/sqlite/omni.db
      - --event-sink-port=8091
      - --bind-addr=0.0.0.0:443
      - --machine-api-bind-addr=0.0.0.0:8090
      - --k8s-proxy-bind-addr=0.0.0.0:8100
      - --advertised-api-url=https://omni.dawidde.de/
      - --machine-api-advertised-url=https://api.omni.dawidde.de
      - --advertised-kubernetes-proxy-url=https://kube.omni.dawidde.de
      - --siderolink-wireguard-advertised-addr=https://omni.dawidde.de:50180
      - --auth-auth0-enabled=false
      - --auth-oidc-enabled=true
      - --auth-oidc-provider-url=${POCKET_ID_ISSUER_URL}
      - --auth-oidc-client-id=${POCKET_ID_CLIENT_ID}
      - --auth-oidc-client-secret=${POCKET_ID_CLIENT_SECRET}
      - --auth-oidc-scopes=openid
      - --auth-oidc-scopes=profile
      - --auth-oidc-scopes=email
      - --initial-users=dawidimb@proton.me
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - omni
    restart: unless-stopped

networks:
  omni:
    name: omni