---
services:
  omni:
    image: ghcr.io/siderolabs/omni:latest
    container_name: omni
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./omni.asc:/omni.asc:ro
      - ./config.yaml:/config.yaml:ro
      - /opt/omni/sqlite:/_out/sqlite:rw
      - /opt/omni/etcd:/_out/etcd:rw
    command:
      --config-path=/config.yaml
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - omni
    restart: unless-stopped

networks:
  omni:
    name: omni