services:
  api:
    endpoint: "0.0.0.0:8080"
    advertisedUrl: "https://omni.domain.de/"
  machineAPI:
    endpoint: "0.0.0.0:8090"
    advertisedUrl: "https://api.omni.domain.de"
  kubernetesProxy:
    endpoint: "0.0.0.0:8100"
    advertisedUrl: "https://kube.omni.domain.de"
  siderolink:
    eventSinkPort: 8091
    wireguard:
      advertisedEndpoint: "ip:50180"

auth:
  initialUsers:
    - "email"
  auth0:
    enabled: false
  oidc:
    enabled: true
    providerUrl: ""
    clientId: ""
    clientSecret: ""
    scopes:
      - openid
      - profile
      - email

storage:
  default:
    etcd:
      privateKeySource: "file:///omni.asc"
  sqlite:
    path: "/_out/sqlite/omni.db"