---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-smb-secrets
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: immich-smb-secrets
  data:
    - secretKey: username
      remoteRef:
        key: kv/kubernetes/immich
        property: smbUser
    - secretKey: password
      remoteRef:
        key: kv/kubernetes/immich
        property: smbPassword