---
- name: Install Proxmox on Heimdall
  hosts: localhost
  tasks:
    - name: Shutdown Server
      dellemc.openmanage.redfish_powerstate:
        baseuri: "192.168.178.2"
        username: ""
        password: ""
        validate_certs: false
        reset_type: "GracefulShutdown"
    - name: Wait for Server to Shutdown
      ansible.builtin.pause:
        seconds: 30
    - name: Attach Proxmox ISO
      dellemc.openmanage.idrac_virtual_media:
        idrac_ip: "192.168.178.2"
        idrac_user: ""
        idrac_password: ""
        validate_certs: false
        force: true
        virtual_media:
          - index: 1
            insert: true
            image: "192.168.178.45:/home/dawid/homelab/heimdall-infra/iso/proxmox.iso"
    - name: Set Virtual Media to boot
      dellemc.openmanage.idrac_boot:
        idrac_ip: "192.168.178.2"
        idrac_user: ""
        idrac_password: ""
        validate_certs: false
        boot_oder:
          - "Virtual CD/DVD"
        boot_source_override_enabled: "once"
        boot_source_override_target: "cd"
        boot_source_override_mode: "uefi"
    - name: Boot Server
      dellemc.openmanage.redfish_powerstate:
        baseuri: "192.168.178.2"
        username: ""
        password: ""
        validate_certs: false
        reset_type: "On"