---
- name: Install Proxmox on Heimdall
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Boot Server to ISO
      dellemc.openmanage.idrac_os_deployment:
        idrac_ip: "192.168.178.2"
        idrac_user: ""
        idrac_password: ""
        validate_certs: false
        share_name: "192.168.178.45:/home/dawid/homelab/heimdall-infra/iso"
        iso_image: "proxmox.iso"
        expose_duration: 180