apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "database-data"
  hostPath:
    path: /var/mnt/zfs/bitwarden/database/data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist