apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-secrets
  namespace: bitwarden
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: bitwarden-secrets
  data:
    - secretKey: globalSettings__installation__id
      remoteRef:
        key: kubernetes/bitwarden
        property: installationId
    - secretKey: globalSettings__installation__key
      remoteRef:
        key: kubernetes/bitwarden
        property: installationKey
    - secretKey: globalSettings__mail__smtp__username
      remoteRef:
        key: kubernetes/bitwarden
        property: mailUsername
    - secretKey: globalSettings__mail__smtp__password
      remoteRef:
        key: kubernetes/bitwarden
        property: mailPassword
    - secretKey: globalSettings__yubico__clientId
      remoteRef:
        key: kubernetes/bitwarden
        property: yubicoClientId
    - secretKey: globalSettings__yubico__key
      remoteRef:
        key: kubernetes/bitwarden
        property: yubicoKey
    - secretKey: SA_PASSWORD
      remoteRef:
        key: kubernetes/bitwarden
        property: saPassword