apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secrets
  namespace: bitwarden
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: smtp-secrets
  data:
  - secretKey: smtp_username
    remoteRef:
      key: kv/Kubernetes
      property: smtp_username
  - secretKey: smtp_password
    remoteRef:
      key: kv/Kubernetes
      property: smtp_password