---
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./data:/vault/file/
    environment:
      - VAULT_ADDR=https://vault.dawidde.de
    cap_add:
      - IPC_LOCK
    network_mode: "host"
    command: server
    restart: always