---
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ./data:/vault/file
      - ./config:/vault/config
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault-http.rule=Host(`vault.dawidde.de`)
      - traefik.http.routers.vault-http.entrypoints=web
      - traefik.http.routers.vault-http.middlewares=vault-https-redirect
      - traefik.http.middlewares.vault-https-redirect.redirectScheme.scheme=https
      - traefik.http.routers.vault-https.rule=Host(`vault.dawidde.de`)
      - traefik.http.routers.vault-https.entrypoints=websecure
      - traefik.http.routers.vault-https.tls=true
      - traefik.http.routers.vault-https.tls.certResolver=cloudflare

networks:
  traefik:
    external: true