---
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/external-domains.yaml:/etc/traefik/external-domains.yaml:ro
      - ./data/certs/:/var/traefik/certs/:rw
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik

networks:
  traefik:
    external: true