---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: full-backup
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  cron: "0 * * * *"
  task: "backup"
  groups:
  - default
  retain: 100
  concurrency: 2