---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-smb-secrets
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: longhorn-smb-secrets
  data:
    - secretKey: CIFS_USERNAME
      remoteRef:
        key: kv/kubernetes/immich
        property: smbUser
    - secretKey: CIFS_PASSWORD
      remoteRef:
        key: kv/kubernetes/immich
        property: smbPassword