apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-panel-caddy-config
  namespace: pelican-panel
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  Caddyfile: |
    {
        admin off
        servers {
            trusted_proxies static private_ranges
        }
    }

    :80 {
        root * /var/www/html/public
        encode gzip

        php_fastcgi 127.0.0.1:9000
        file_server
    }