apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-panel-data
  namespace: pelican-panel
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi