---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  destination:
    namespace: home-assistant
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/DawidDe/homelab.git'
    targetRevision: HEAD
    path: base/kubernetes/home-assistant
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true