---
apiVersion: traefik.io/v1alpha1
kind: ServersTCP
metadata:
  name: home-assistant-tcp-backend
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  servers:
    - address: 192.168.178.6:8123