---
apiVersion: v1
kind: TCPService
metadata:
  name: home-assistant-service
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  weighted:
    services:
      - name: home-assistant-service-backend